/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PathRouteImport } from './routes/$path'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as PreviewPresentationRouteImport } from './routes/preview/presentation'
import { Route as PreviewMinimalRouteImport } from './routes/preview/minimal'
import { Route as PreviewDelftRouteImport } from './routes/preview/delft'
import { Route as DocsDocsPathRouteImport } from './routes/docs/$docsPath'

const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/$path',
  path: '/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const PreviewPresentationRoute = PreviewPresentationRouteImport.update({
  id: '/preview/presentation',
  path: '/preview/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewMinimalRoute = PreviewMinimalRouteImport.update({
  id: '/preview/minimal',
  path: '/preview/minimal',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDelftRoute = PreviewDelftRouteImport.update({
  id: '/preview/delft',
  path: '/preview/delft',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocsPathRoute = DocsDocsPathRouteImport.update({
  id: '/$docsPath',
  path: '/$docsPath',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$path': typeof PathRoute
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/docs/$docsPath': typeof DocsDocsPathRoute
  '/preview/delft': typeof PreviewDelftRoute
  '/preview/minimal': typeof PreviewMinimalRoute
  '/preview/presentation': typeof PreviewPresentationRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$path': typeof PathRoute
  '/examples': typeof ExamplesRoute
  '/docs/$docsPath': typeof DocsDocsPathRoute
  '/preview/delft': typeof PreviewDelftRoute
  '/preview/minimal': typeof PreviewMinimalRoute
  '/preview/presentation': typeof PreviewPresentationRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$path': typeof PathRoute
  '/docs': typeof DocsRouteWithChildren
  '/examples': typeof ExamplesRoute
  '/docs/$docsPath': typeof DocsDocsPathRoute
  '/preview/delft': typeof PreviewDelftRoute
  '/preview/minimal': typeof PreviewMinimalRoute
  '/preview/presentation': typeof PreviewPresentationRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$path'
    | '/docs'
    | '/examples'
    | '/docs/$docsPath'
    | '/preview/delft'
    | '/preview/minimal'
    | '/preview/presentation'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$path'
    | '/examples'
    | '/docs/$docsPath'
    | '/preview/delft'
    | '/preview/minimal'
    | '/preview/presentation'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/$path'
    | '/docs'
    | '/examples'
    | '/docs/$docsPath'
    | '/preview/delft'
    | '/preview/minimal'
    | '/preview/presentation'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathRoute: typeof PathRoute
  DocsRoute: typeof DocsRouteWithChildren
  ExamplesRoute: typeof ExamplesRoute
  PreviewDelftRoute: typeof PreviewDelftRoute
  PreviewMinimalRoute: typeof PreviewMinimalRoute
  PreviewPresentationRoute: typeof PreviewPresentationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$path': {
      id: '/$path'
      path: '/$path'
      fullPath: '/$path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/preview/presentation': {
      id: '/preview/presentation'
      path: '/preview/presentation'
      fullPath: '/preview/presentation'
      preLoaderRoute: typeof PreviewPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/minimal': {
      id: '/preview/minimal'
      path: '/preview/minimal'
      fullPath: '/preview/minimal'
      preLoaderRoute: typeof PreviewMinimalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/delft': {
      id: '/preview/delft'
      path: '/preview/delft'
      fullPath: '/preview/delft'
      preLoaderRoute: typeof PreviewDelftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$docsPath': {
      id: '/docs/$docsPath'
      path: '/$docsPath'
      fullPath: '/docs/$docsPath'
      preLoaderRoute: typeof DocsDocsPathRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsDocsPathRoute: typeof DocsDocsPathRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocsPathRoute: DocsDocsPathRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathRoute: PathRoute,
  DocsRoute: DocsRouteWithChildren,
  ExamplesRoute: ExamplesRoute,
  PreviewDelftRoute: PreviewDelftRoute,
  PreviewMinimalRoute: PreviewMinimalRoute,
  PreviewPresentationRoute: PreviewPresentationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
